INSERT INTO `goods` VALUES (1, '蓝莓平衡保湿霜', ' <img src=\"./IMG/ShopImg/balance1.png\" alt=\"\">', 999, 98);
INSERT INTO `goods` VALUES (2, '蓝莓平衡保湿卸妆水', ' <img src=\"./IMG/ShopImg/balance2.png\" alt=\"\">', 999, 78);
INSERT INTO `goods` VALUES (3, '蓝莓平衡保湿套装', ' <img src=\"./IMG/ShopImg/balance3.png\" alt=\"\">', 999, 224);
INSERT INTO `goods` VALUES (4, '蓝莓平衡保湿调料乳', ' <img src=\"./IMG/ShopImg/balance4.png\" alt=\"\">', 999, 88);
INSERT INTO `goods` VALUES (5, '蓝莓保湿平衡调理水', '<img src=\"./IMG/ShopImg/balance5.png\" alt=\"\">', 999, 88);
INSERT INTO `goods` VALUES (6, '蓝莓平衡弱酸性洁面膏', '<img src=\"./IMG/ShopImg/balance6.png\" alt=\"\">', 999, 48);
INSERT INTO `goods` VALUES (7, '火山岩泥毛孔清洁倍净多效慕斯面膜特别套装[飞跃限量版]', '<img src=\"./IMG/ShopImg/feiyue1.png\" alt=\"\">', 999, 150);
INSERT INTO `goods` VALUES (8, '火山岩泥毛孔清洁倍净多效面膜 [飞跃限量版]', '<img src=\"./IMG/ShopImg/feiyue2.png\" alt=\"\">', 999, 109);
INSERT INTO `goods` VALUES (9, '火山岩泥毛孔清洁多效倍净洁颜乳 [飞跃限量版]', '<img src=\"./IMG/ShopImg/feiyue3.png\" alt=\"\">', 999, 80);
INSERT INTO `goods` VALUES (10, '火山岩泥毛孔清洁多效倍净洁肤液 [飞跃限量版]', ' <img src=\"./IMG/ShopImg/feiyue4.png\" alt=\"\">', 999, 100);
INSERT INTO `goods` VALUES (11, '臻选保湿防晒霜 [飞跃限量版] SPF50+ PA+++', '<img src=\"./IMG/ShopImg/feiyue5.png\" alt=\"\">', 999, 140);
INSERT INTO `goods` VALUES (12, '臻选保湿防晒乳 [飞跃限量版] SPF50+ PA+++', '<img src=\"./IMG/ShopImg/feiyue6.png\" alt=\"\">', 999, 140);
INSERT INTO `goods` VALUES (13, '自然关爱日护防晒霜[温和型]', '<img src=\"./IMG/ShopImg/fs1.png\" alt=\"\">', 999, 70);
INSERT INTO `goods` VALUES (14, '自然关爱优颜防晒露 [清爽型]', ' <img src=\"./IMG/ShopImg/fs2.png\" alt=\"\">', 999, 140);
INSERT INTO `goods` VALUES (15, '自然关爱臻选防晒霜 [户外型]', '  <img src=\"./IMG/ShopImg/fs3.png\" alt=\"\">', 999, 140);
INSERT INTO `goods` VALUES (16, '自然关爱优颜防晒霜 [保湿型]', ' <img src=\"./IMG/ShopImg/fs4.png\" alt=\"\">', 999, 100);
INSERT INTO `goods` VALUES (17, '自然关爱优颜防晒霜 [控油型]', '<img src=\"./IMG/ShopImg/fs5.png\" alt=\"\">', 999, 100);
INSERT INTO `goods` VALUES (18, '自然关爱优颜防晒棒 [控油型]', '<img src=\"./IMG/ShopImg/fs6.png\" alt=\"\">', 999, 150);
INSERT INTO `goods` VALUES (19, '自然关爱优颜防晒气垫霜 [美白型]', '<img src=\"./IMG/ShopImg/fs7.png\" alt=\"\">', 999, 120);
INSERT INTO `goods` VALUES (20, '自然关爱优颜防晒乳液 [控油]', '<img src=\"./IMG/ShopImg/fs8.png\" alt=\"\">', 999, 120);
INSERT INTO `goods` VALUES (21, '自然关爱优颜防晒霜 [多效型]', '<img src=\"./IMG/ShopImg/fs9.png\" alt=\"\">', 999, 110);
INSERT INTO `goods` VALUES (22, '臻选保湿防晒乳 [飞跃限量版] SPF50+ PA+++', '<img src=\"./IMG/ShopImg/fs10.png\" alt=\"\">', 999, 140);
INSERT INTO `goods` VALUES (23, '白牡丹焕妍晶白淡斑精华露', ' <img src=\"./IMG/ShopImg/bai1.png\" alt=\"\">', 999, 240);
INSERT INTO `goods` VALUES (24, '白牡丹焕妍晶白精华液亮肤套装 白光瓶', '  <img src=\"./IMG/ShopImg/bai2.png\" alt=\"\">', 999, 240);
INSERT INTO `goods` VALUES (25, '白牡丹焕妍晶采精华液鲜注面膜 5片装', '<img src=\"./IMG/ShopImg/bai3.png\" alt=\"\">', 999, 125);
INSERT INTO `goods` VALUES (26, '白牡丹焕妍晶白眼部精华露', '<img src=\"./IMG/ShopImg/bai4.png\" alt=\"\">', 999, 220);
INSERT INTO `goods` VALUES (27, '白牡丹焕妍晶白亮肤水', '<img src=\"./IMG/ShopImg/bai5.png\" alt=\"\">', 999, 260);
INSERT INTO `goods` VALUES (28, '白牡丹焕妍晶采气垫粉底液', '<img src=\"./IMG/ShopImg/bai6.png\" alt=\"\">', 999, 218);
INSERT INTO `goods` VALUES (29, '白牡丹焕妍晶白素颜面霜 素颜霜', '<img src=\"./IMG/ShopImg/bai7.png\" alt=\"\">', 999, 195);
INSERT INTO `goods` VALUES (30, '白牡丹焕妍晶采洁面啫喱', ' <img src=\"./IMG/ShopImg/bai8.png\" alt=\"\">', 999, 80);
INSERT INTO `goods` VALUES (31, '白牡丹焕妍晶白水分面霜', '<img src=\"./IMG/ShopImg/bai9.png\" alt=\"\">', 999, 220);
INSERT INTO `goods` VALUES (32, '自然关爱日护防晒霜[温和型]', '<img src=\"./IMG/ShopImg/bai10.png\" alt=\"\">', 999, 140);
